version = 0.1
[default.deploy.parameters]
stack_name = "sfn-eb-demo-test"
resolve_s3 = true
s3_prefix = "sfn-eb-demo-test"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "MongoDBDataURL=\"https://data.mongodb-api.com/app/data-whpzf/endpoint/data/beta/action/insertOne\" MyAPIKeyName=\"MDBAPI\" MongoDBCustomEventBus=\"MDB-test\""
image_repositories = []
